/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador_Instrucciones;

/**
 *
 * @author DEIBER
 */
public class GUI_Instrucciones extends javax.swing.JFrame {
    
    private Controlador_Instrucciones controlador_Instrucciones;

    /**
     * Creates new form GUI_Instrucciones
     */
    public GUI_Instrucciones() {
         initComponents();
        setTitle("Diquis y las Petroesferas");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        controlador_Instrucciones= new Controlador_Instrucciones(this);
        btn_Volver.addActionListener(controlador_Instrucciones);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVolver.png"))); // NOI18N
        btn_Volver.setActionCommand("Volver");
        btn_Volver.setBorderPainted(false);
        btn_Volver.setContentAreaFilled(false);
        getContentPane().add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 210, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaHist.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Volver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
