/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador_Principal;

/**
 *
 * @author DEIBER
 */
public class GUI_Principal extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Principal
     */
    public GUI_Principal() {
        initComponents();
        setTitle("Diquis y las Petroesferas");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        Controlador_Principal controlador_Principal= new Controlador_Principal(this);
        escuchar(controlador_Principal);
    }
    
    public void escuchar(Controlador_Principal controlador_Principal){
        btn_Jugar.addActionListener(controlador_Principal);
        btn_Instrucciones.addActionListener(controlador_Principal);
        btn_Record.addActionListener(controlador_Principal);
        btn_Salir.addActionListener(controlador_Principal);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Jugar = new javax.swing.JButton();
        btn_Instrucciones = new javax.swing.JButton();
        btn_Record = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonPlay.png"))); // NOI18N
        btn_Jugar.setActionCommand("Jugar");
        btn_Jugar.setBorderPainted(false);
        btn_Jugar.setContentAreaFilled(false);
        getContentPane().add(btn_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 230, 110));

        btn_Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton indicaciones.png"))); // NOI18N
        btn_Instrucciones.setActionCommand("Instrucciones");
        btn_Instrucciones.setBorderPainted(false);
        btn_Instrucciones.setContentAreaFilled(false);
        getContentPane().add(btn_Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        btn_Record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonRecord.png"))); // NOI18N
        btn_Record.setActionCommand("Record");
        btn_Record.setBorderPainted(false);
        btn_Record.setContentAreaFilled(false);
        getContentPane().add(btn_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton salir.png"))); // NOI18N
        btn_Salir.setActionCommand("Salir");
        btn_Salir.setBorderPainted(false);
        btn_Salir.setContentAreaFilled(false);
        getContentPane().add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Personaje Principal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Instrucciones;
    private javax.swing.JButton btn_Jugar;
    private javax.swing.JButton btn_Record;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
