/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador_Juego;

/**
 *
 * @author DEIBER
 */
public class GUI_Juego extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Juego
     */
    public GUI_Juego() {
        initComponents();
    }
    
    public void setControlador(Controlador_Juego controlador_Juego){
    this.addKeyListener(controlador_Juego);
    }
    public Panel_Juego getPanelJuego(){
    return panel_Juego1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Juego1 = new vista.Panel_Juego();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panel_Juego1Layout = new javax.swing.GroupLayout(panel_Juego1);
        panel_Juego1.setLayout(panel_Juego1Layout);
        panel_Juego1Layout.setHorizontalGroup(
            panel_Juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panel_Juego1Layout.setVerticalGroup(
            panel_Juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(panel_Juego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Panel_Juego panel_Juego1;
    // End of variables declaration//GEN-END:variables
}
