/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Controlador_Juego;
import java.awt.Graphics;
import modelo.Principal;

/**
 *
 * @author DEIBER
 */
public class Panel_Juego extends javax.swing.JPanel {

    private Graphics g;
    private Principal personaje_Principal;
    private Controlador_Juego controlador_Juego;

    /**
     * Creates new form Panel_Juego
     */
    public Panel_Juego() {
        initComponents();
        controlador_Juego = new Controlador_Juego(this);
        this.addKeyListener(controlador_Juego);
        this.addMouseListener(controlador_Juego);
    }

    public Controlador_Juego getControladorGUIJuego() {
        return controlador_Juego;
    }

    public void setControlador(Controlador_Juego controlador_Juego) {
        this.controlador_Juego = controlador_Juego;
    }

    public void repaint(Graphics g) {
        controlador_Juego.dibujar(g);

    }
    
    @Override
public void paint(Graphics g){
    super.paintComponent(g);
       controlador_Juego.dibujar(g);
    //fondo.paintIcon(null,g,0,0);
    //personajePrincipal.show(g);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
